version: '3.8'
services:
  api:
    container_name: sc_phoenix_web
    build: .
    environment:
      FLASK_ENV: development
    expose:
      - 7080
    depends_on:
      - mysql
    links:
      - mysql
    command: [sh, -c, "flask run -h 0.0.0.0 -p 7080"]
    volumes:
      - ./:/app
  mysql:
    image: mysql:8.0.21
    container_name: sc_phoenix_sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - ./db/sc-phoenix.db:/docker-entrypoint-initdb.d/sc-phoenix.db
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
  nginx:
    build:
      dockerfile: ./Dockerfile.nginx
      context: .
    restart: always
    container_name: nginx
    command: [sh, -c, "/docker-wait && nginx -g 'daemon off;'"]
    ports:
      - 80:80
    environment:
      - WAIT_HOSTS=api:7080
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=10
